### ISSUE TITLE
[QUESTION] Support for this project

### ISSUE THREAD

**Issue by williamsbdev** [caffeinehit/django-oauth2-provider#123]
Thank you very much for the project. Just curious if work on this project has been discontinued. I see that there has not been a commit on master in over 16 months. This might indicate that the project maintainers have moved on. If so, what are the maintainers using? I've seen in the comments of issues and PRs references to [django-oauth-toolkit](https://github.com/evonove/django-oauth-toolkit) as a viable solution. It appears to be more actively maintained with more contributors and greater throughput on issues.

Please advise as to the state of this project. If the project is not actively maintained, it might be helpful to put that in the README.md.

Thanks again for the OSS.

**Comment by NicoHinderling** [comment]
Bump. I wish I had seen this as well.

**Comment by blag** [comment]
This project is dead. Please see https://github.com/caffeinehit/django-oauth2-provider/issues/119#issuecomment-76118642 for more information.
