### ISSUE TITLE
Single access token mode - token expiry and refresh

### ISSUE THREAD

**Issue by Geekfish** [caffeinehit/django-oauth2-provider#70]
When `OAUTH_SINGLE_ACCESS_TOKEN` is set to `True` then instead of always creating a new token we check whether one with the same client user and scope already exists and we return that instead:

```
def get_access_token(self, request, user, scope, client):
    try:
        # Attempt to fetch an existing access token.
        at = AccessToken.objects.get(user=user, client=client, scope=scope)
    except AccessToken.DoesNotExist:
        # None found... make a new one!
        at = self.create_access_token(request, user, scope, client)
        self.create_refresh_token(request, user, scope, at, client)
    return at
```

Note that this does not check for token expiry when fetching the access token.

If `OAUTH_DELETE_EXPIRED` is set to `False` (default) then if we hit the access_token endpoint with grant_type=refresh_token and pass the refresh token from a previous access token then the refresh process will just create a second access token:

```
def refresh_token(self, request, data, client):
    """
    Handle ``grant_type=refresh_token`` requests as defined in :rfc:`6`.
    """
    rt = self.get_refresh_token_grant(request, data, client)

    # this must be called first in case we need to purge expired tokens
    self.invalidate_refresh_token(rt)
    self.invalidate_access_token(rt.access_token)

    at = self.create_access_token(request, rt.user, rt.access_token.scope,
            client)
    rt = self.create_refresh_token(request, at.user, at.scope, at, client)

    return self.access_token_response(at)
```

The `invalidate_access_token` function will just set the expiry date and we end up with 2 access tokens in our db with the same client, user and scope.
This results in `get_access_token` above bombing out at
`AccessToken.objects.get(user=user, client=client, scope=scope)`
with a multiple objects returned error.

I think that `OAUTH_SINGLE_ACCESS_TOKEN` should either automatically enable  `OAUTH_DELETE_EXPIRED` or at a minimum I think the old access token should be deleted on refresh.

I'm happy to reopen this as a pull request if the above solution sounds good.

**Comment by SilviyaRepo** [comment]
Hi , how could I achieve this using Oauth Tool Kit?
